### ISSUE TITLE
remoteEntry.js not found

### ISSUE THREAD

**Issue by arnee** [mercedes-benz/DnA#1914]
When running the project locally from the `dev` branch with docker-compose I get an error in the frontend under `http://localhost:8080`:
The frontend tries unsuccessfully to load `remoteEntry.js` from

- `http://localhost:8084/remoteEntry.js`
- `http://localhost:8085/remoteEntry.js`
- `http://localhost:8086/remoteEntry.js`

**Comment by agnelpraveen** [comment]
Thanks for finding this issue.

Currently, in the dev docker-compose we have not included our new services Chronos, DSS and Data Product.

But, Since dev branch contains all the development code the frontend package trying to load these new services. 

Generally, it won't affect the current code/docker-compose to work.

After testing we soon add these new services in the docker-compose.
